### ISSUE TITLE
seems like you might need to ship with dependencies

### ISSUE THREAD

**Issue by WJP2003** [HelenaMKG/umquilt#2]
![image](https://user-images.githubusercontent.com/31232449/120948783-9ea1c600-c708-11eb-83d6-70b0a9453d46.png)
![image](https://user-images.githubusercontent.com/31232449/120948803-a3667a00-c708-11eb-8f8e-4956e60c0035.png)

**Comment by HelenaMKG** [comment]
Indeed. Will be fixed in 0.3

**Comment by HelenaMKG** [comment]
Fixed in latest package.
